/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_temperature_measurement        21
#define gattdb_temp_descriptor                23
#define gattdb_temperature_type               25
#define gattdb_measurement_interval           27
#define gattdb_valid_range                    29
#define gattdb_light_measurement              32
#define gattdb_light_descriptor               34
#define gattdb_sound_measurement              37
#define gattdb_sound_descriptor               39
#define gattdb_sleep_time                     42
#define gattdb_sleep_hours                    45
#define gattdb_sleep_hours_descriptor         47
#define gattdb_ota_control                    50


#endif // __GATT_DB_H
